/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'Home': RouteRecordInfo<
      'Home',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '404': RouteRecordInfo<
      '404',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    'Activity': RouteRecordInfo<
      'Activity',
      '/activity',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Buy': RouteRecordInfo<
      'Buy',
      '/buy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'BuyHistory': RouteRecordInfo<
      'BuyHistory',
      '/buy/history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'BuyUsdt': RouteRecordInfo<
      'BuyUsdt',
      '/buy/usdt',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Charts': RouteRecordInfo<
      'Charts',
      '/charts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Counter': RouteRecordInfo<
      'Counter',
      '/counter',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Faq': RouteRecordInfo<
      'Faq',
      '/faq',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'FaqDetail': RouteRecordInfo<
      'FaqDetail',
      '/faq/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'KeepAlive': RouteRecordInfo<
      'KeepAlive',
      '/keepalive',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Login': RouteRecordInfo<
      'Login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Mock': RouteRecordInfo<
      'Mock',
      '/mock',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'News': RouteRecordInfo<
      'News',
      '/news',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'NewsDetail': RouteRecordInfo<
      'NewsDetail',
      '/news/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'Pay': RouteRecordInfo<
      'Pay',
      '/pay',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ProductDetail': RouteRecordInfo<
      'ProductDetail',
      '/product/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'Profile': RouteRecordInfo<
      'Profile',
      '/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'BankCard': RouteRecordInfo<
      'BankCard',
      '/profile/bank-card',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/profile/change-password': RouteRecordInfo<
      '/profile/change-password',
      '/profile/change-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Chat': RouteRecordInfo<
      'Chat',
      '/profile/chat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Collection': RouteRecordInfo<
      'Collection',
      '/profile/collection',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/profile/fund-details': RouteRecordInfo<
      '/profile/fund-details',
      '/profile/fund-details',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/profile/order-record': RouteRecordInfo<
      '/profile/order-record',
      '/profile/order-record',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/profile/recharge-record': RouteRecordInfo<
      '/profile/recharge-record',
      '/profile/recharge-record',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/profile/repurchase-record': RouteRecordInfo<
      '/profile/repurchase-record',
      '/profile/repurchase-record',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/profile/withdraw-record': RouteRecordInfo<
      '/profile/withdraw-record',
      '/profile/withdraw-record',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Register': RouteRecordInfo<
      'Register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'RegisterInvite': RouteRecordInfo<
      'RegisterInvite',
      '/register/:inviteCode',
      { inviteCode: ParamValue<true> },
      { inviteCode: ParamValue<false> },
      | never
    >,
    'DailyBuyInrRewards': RouteRecordInfo<
      'DailyBuyInrRewards',
      '/rewards/daily-buy-inr',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'LinkUpiRewards': RouteRecordInfo<
      'LinkUpiRewards',
      '/rewards/link-upi',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'NewbieRewards': RouteRecordInfo<
      'NewbieRewards',
      '/rewards/newbie',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ScrollCache': RouteRecordInfo<
      'ScrollCache',
      '/scroll-cache',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Sell': RouteRecordInfo<
      'Sell',
      '/sell',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'SellHistory': RouteRecordInfo<
      'SellHistory',
      '/sell/history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'stats': RouteRecordInfo<
      'stats',
      '/sell/stats',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Settings': RouteRecordInfo<
      'Settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Team': RouteRecordInfo<
      'Team',
      '/team',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'InviteFriendsRewards': RouteRecordInfo<
      'InviteFriendsRewards',
      '/team/invite-rewards',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'TeamMembers': RouteRecordInfo<
      'TeamMembers',
      '/team/members',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'RecallRewards': RouteRecordInfo<
      'RecallRewards',
      '/team/recall-rewards',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'UnoCSS': RouteRecordInfo<
      'UnoCSS',
      '/unocss',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'UPI': RouteRecordInfo<
      'UPI',
      '/upi',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'UpiDetail': RouteRecordInfo<
      'UpiDetail',
      '/upi/detail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'LinkUpi': RouteRecordInfo<
      'LinkUpi',
      '/upi/link',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | 'Home'
      views:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '404'
      views:
        | never
    }
    'src/pages/activity/index.vue': {
      routes:
        | 'Activity'
      views:
        | never
    }
    'src/pages/buy/index.vue': {
      routes:
        | 'Buy'
      views:
        | never
    }
    'src/pages/buy/history.vue': {
      routes:
        | 'BuyHistory'
      views:
        | never
    }
    'src/pages/buy/usdt.vue': {
      routes:
        | 'BuyUsdt'
      views:
        | never
    }
    'src/pages/charts/index.vue': {
      routes:
        | 'Charts'
      views:
        | never
    }
    'src/pages/counter/index.vue': {
      routes:
        | 'Counter'
      views:
        | never
    }
    'src/pages/faq/index.vue': {
      routes:
        | 'Faq'
      views:
        | never
    }
    'src/pages/faq/[id].vue': {
      routes:
        | 'FaqDetail'
      views:
        | never
    }
    'src/pages/keepalive/index.vue': {
      routes:
        | 'KeepAlive'
      views:
        | never
    }
    'src/pages/login/index.vue': {
      routes:
        | 'Login'
      views:
        | never
    }
    'src/pages/mock/index.vue': {
      routes:
        | 'Mock'
      views:
        | never
    }
    'src/pages/news/index.vue': {
      routes:
        | 'News'
      views:
        | never
    }
    'src/pages/news/[id].vue': {
      routes:
        | 'NewsDetail'
      views:
        | never
    }
    'src/pages/pay/index.vue': {
      routes:
        | 'Pay'
      views:
        | never
    }
    'src/pages/product/[id].vue': {
      routes:
        | 'ProductDetail'
      views:
        | never
    }
    'src/pages/profile/index.vue': {
      routes:
        | 'Profile'
      views:
        | never
    }
    'src/pages/profile/bank-card.vue': {
      routes:
        | 'BankCard'
      views:
        | never
    }
    'src/pages/profile/change-password.vue': {
      routes:
        | '/profile/change-password'
      views:
        | never
    }
    'src/pages/profile/chat.vue': {
      routes:
        | 'Chat'
      views:
        | never
    }
    'src/pages/profile/collection.vue': {
      routes:
        | 'Collection'
      views:
        | never
    }
    'src/pages/profile/fund-details.vue': {
      routes:
        | '/profile/fund-details'
      views:
        | never
    }
    'src/pages/profile/order-record.vue': {
      routes:
        | '/profile/order-record'
      views:
        | never
    }
    'src/pages/profile/recharge-record.vue': {
      routes:
        | '/profile/recharge-record'
      views:
        | never
    }
    'src/pages/profile/repurchase-record.vue': {
      routes:
        | '/profile/repurchase-record'
      views:
        | never
    }
    'src/pages/profile/withdraw-record.vue': {
      routes:
        | '/profile/withdraw-record'
      views:
        | never
    }
    'src/pages/register/index.vue': {
      routes:
        | 'Register'
      views:
        | never
    }
    'src/pages/register/[inviteCode].vue': {
      routes:
        | 'RegisterInvite'
      views:
        | never
    }
    'src/pages/rewards/daily-buy-inr.vue': {
      routes:
        | 'DailyBuyInrRewards'
      views:
        | never
    }
    'src/pages/rewards/link-upi.vue': {
      routes:
        | 'LinkUpiRewards'
      views:
        | never
    }
    'src/pages/rewards/newbie.vue': {
      routes:
        | 'NewbieRewards'
      views:
        | never
    }
    'src/pages/scroll-cache/index.vue': {
      routes:
        | 'ScrollCache'
      views:
        | never
    }
    'src/pages/sell/index.vue': {
      routes:
        | 'Sell'
      views:
        | never
    }
    'src/pages/sell/history.vue': {
      routes:
        | 'SellHistory'
      views:
        | never
    }
    'src/pages/sell/stats.vue': {
      routes:
        | 'stats'
      views:
        | never
    }
    'src/pages/settings/index.vue': {
      routes:
        | 'Settings'
      views:
        | never
    }
    'src/pages/team/index.vue': {
      routes:
        | 'Team'
      views:
        | never
    }
    'src/pages/team/invite-rewards.vue': {
      routes:
        | 'InviteFriendsRewards'
      views:
        | never
    }
    'src/pages/team/members.vue': {
      routes:
        | 'TeamMembers'
      views:
        | never
    }
    'src/pages/team/recall-rewards.vue': {
      routes:
        | 'RecallRewards'
      views:
        | never
    }
    'src/pages/unocss/index.vue': {
      routes:
        | 'UnoCSS'
      views:
        | never
    }
    'src/pages/upi/index.vue': {
      routes:
        | 'UPI'
      views:
        | never
    }
    'src/pages/upi/detail.vue': {
      routes:
        | 'UpiDetail'
      views:
        | never
    }
    'src/pages/upi/link.vue': {
      routes:
        | 'LinkUpi'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
